# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aidan/Desktop/High_Preformance_Computer_Graphics/Lab1-RayTracing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aidan/Desktop/High_Preformance_Computer_Graphics/Lab1-RayTracing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aidan/Desktop/High_Preformance_Computer_Graphics/Lab1-RayTracing/CMakeFiles /Users/aidan/Desktop/High_Preformance_Computer_Graphics/Lab1-RayTracing//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aidan/Desktop/High_Preformance_Computer_Graphics/Lab1-RayTracing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raytracer

# Build rule for target.
raytracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raytracer
.PHONY : raytracer

# fast build rule for target.
raytracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/build
.PHONY : raytracer/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/main.cpp.s
.PHONY : main.cpp.s

swCamera.o: swCamera.cpp.o
.PHONY : swCamera.o

# target to build an object file
swCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swCamera.cpp.o
.PHONY : swCamera.cpp.o

swCamera.i: swCamera.cpp.i
.PHONY : swCamera.i

# target to preprocess a source file
swCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swCamera.cpp.i
.PHONY : swCamera.cpp.i

swCamera.s: swCamera.cpp.s
.PHONY : swCamera.s

# target to generate assembly for a file
swCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swCamera.cpp.s
.PHONY : swCamera.cpp.s

swIntersection.o: swIntersection.cpp.o
.PHONY : swIntersection.o

# target to build an object file
swIntersection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swIntersection.cpp.o
.PHONY : swIntersection.cpp.o

swIntersection.i: swIntersection.cpp.i
.PHONY : swIntersection.i

# target to preprocess a source file
swIntersection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swIntersection.cpp.i
.PHONY : swIntersection.cpp.i

swIntersection.s: swIntersection.cpp.s
.PHONY : swIntersection.s

# target to generate assembly for a file
swIntersection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swIntersection.cpp.s
.PHONY : swIntersection.cpp.s

swScene.o: swScene.cpp.o
.PHONY : swScene.o

# target to build an object file
swScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swScene.cpp.o
.PHONY : swScene.cpp.o

swScene.i: swScene.cpp.i
.PHONY : swScene.i

# target to preprocess a source file
swScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swScene.cpp.i
.PHONY : swScene.cpp.i

swScene.s: swScene.cpp.s
.PHONY : swScene.s

# target to generate assembly for a file
swScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swScene.cpp.s
.PHONY : swScene.cpp.s

swSphere.o: swSphere.cpp.o
.PHONY : swSphere.o

# target to build an object file
swSphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swSphere.cpp.o
.PHONY : swSphere.cpp.o

swSphere.i: swSphere.cpp.i
.PHONY : swSphere.i

# target to preprocess a source file
swSphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swSphere.cpp.i
.PHONY : swSphere.cpp.i

swSphere.s: swSphere.cpp.s
.PHONY : swSphere.s

# target to generate assembly for a file
swSphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swSphere.cpp.s
.PHONY : swSphere.cpp.s

swTriangle.o: swTriangle.cpp.o
.PHONY : swTriangle.o

# target to build an object file
swTriangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swTriangle.cpp.o
.PHONY : swTriangle.cpp.o

swTriangle.i: swTriangle.cpp.i
.PHONY : swTriangle.i

# target to preprocess a source file
swTriangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swTriangle.cpp.i
.PHONY : swTriangle.cpp.i

swTriangle.s: swTriangle.cpp.s
.PHONY : swTriangle.s

# target to generate assembly for a file
swTriangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/raytracer.dir/build.make CMakeFiles/raytracer.dir/swTriangle.cpp.s
.PHONY : swTriangle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... raytracer"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... swCamera.o"
	@echo "... swCamera.i"
	@echo "... swCamera.s"
	@echo "... swIntersection.o"
	@echo "... swIntersection.i"
	@echo "... swIntersection.s"
	@echo "... swScene.o"
	@echo "... swScene.i"
	@echo "... swScene.s"
	@echo "... swSphere.o"
	@echo "... swSphere.i"
	@echo "... swSphere.s"
	@echo "... swTriangle.o"
	@echo "... swTriangle.i"
	@echo "... swTriangle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

